vim.api.nvim_create_user_command(       'CMakeClean', CleanCMakeBuild, {})
vim.api.nvim_create_user_command(         'CMakeDir', SetWorkingDir, {})
vim.api.nvim_create_user_command(    'CMakeSetDebug', function() SetBuildMode("Debug") end, {})
vim.api.nvim_create_user_command(  'CMakeSetRelease', function() SetBuildMode("Release") end, {})
vim.api.nvim_create_user_command(    'CMakeGenerate', GenerateBuildFiles, {})
vim.api.nvim_create_user_command(       'CMakeTrace', GenerateBuildFilesTraced, {})
vim.api.nvim_create_user_command(       'CMakeBuild', BuildCMakeProject, {})
vim.api.nvim_create_user_command(         'CMakeRun', RunProgram, {})
vim.api.nvim_create_user_command(     'CMakeInstall', CMakeInstallProject, {})
vim.api.nvim_create_user_command('CMakeSetBuildmode', function(opts) SetBuildMode(opts.args) end, { nargs = 1 })
vim.api.nvim_create_user_command(         'CMakeJob', CMakeBuildAndRun, {})
vim.api.nvim_create_user_command(     'RunUnitTests', RunTests, {})
